RelationalPlan.clone() causes NullPointerException when cloning BatchedUpdatePlan
When executing a new unit test which used a BatchedUpdateCommand with a PreparedStatement the following error would occur when executing ProcessorPlan.clone() using a plan of type BatchedUpdatePlan:

BatchedUpdatePlan {
ProjectNode(2) output=["Count"] ["Count"]
  BatchedUpdateNode(3) output=["Count"] 

}


java.lang.RuntimeException: java.lang.NullPointerException
	at com.metamatrix.query.processor.TestProcessor.helpProcess(TestProcessor.java:224)
	at org.teiid.dqp.internal.process.TestPreparedStatement.helpTestProcessing(TestPreparedStatement.java:127)
	at org.teiid.dqp.internal.process.TestPreparedStatementBatchedUpdate.testProcessor_VarNumCmds(TestPreparedStatementBatchedUpdate.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
Caused by: java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:131)
	at com.metamatrix.query.processor.relational.RelationalPlan.clone(RelationalPlan.java:136)
	at com.metamatrix.query.processor.batch.BatchedUpdatePlan.clone(BatchedUpdatePlan.java:83)
	at com.metamatrix.query.processor.TestProcessor.helpProcess(TestProcessor.java:214)
	... 21 more


It appears that in the test case outputCols is null in the ProjectNode of the relational plan which then results in the clone of outputcols to fail due to it being used as a parameter to the creation of the new ArrayList.
